### ISSUE TITLE
Sumo monitoring problems when using free sumo account

### ISSUE THREAD

**Issue by snap4ward** [jeff-d/quicklab#1]
It appears that the lookup tables are not available in the free account.  Is there a work around or must I use a full account to play with quick labse?

 Error: {"id":"KWB1A-ND8B2-RX15P","errors":[{"code":"lookup:invalid_request","message":"Invalid lookup table request.","detail":"Scalable Lookups is not available in your account type."}]}
│
│   with module.sumo["gewq"].sumologic_lookup_table.aws_admins,
│   on modules/sumo/cloudtrail.tf line 99, in resource "sumologic_lookup_table" "aws_admins":
│   99: resource "sumologic_lookup_table" "aws_admins" {

**Comment by jeff-d** [comment]
Hello! Unfortunately Lookup Tables today are not available in Sumo Logic Free ([reference](https://help.sumologic.com/docs/search/lookup-tables/create-lookup-table/#how-many-lookup-tables-can-you-have)). 

That said, the QuickLab implication of this Sumo limitation is pretty small, e.g. the Administrator Activty panels of the [CloudTrail App](https://help.sumologic.com/docs/integrations/amazon-aws/cloudtrail/#enable-sumo-logic-to-track-aws-admin-activity) will not show results (as in similar to [this screenshot](https://help.sumologic.com/docs/integrations/amazon-aws/cloudtrail/#aws-cloudtrail---user-monitoring)). 

Currently the only workaround would be to comment out or remove the terraform `resource "sumologic_lookup_table" "aws_admins" {...}` (see _aws/modules/sumo/terraform.tf_).

This is worth calling out more explicitly in the [QuickLab docs](https://github.com/jeff-d/quicklab/blob/main/docs/monitoring.md#aws-general).
