### ISSUE TITLE
With sumo enabled I receive the following error "Field with the given name already exists"  in the otc section.

### ISSUE THREAD

**Issue by snap4ward** [jeff-d/quicklab#2]
While I can fully deploy quicklabs with montoring=none, if I enable sumo monitoring, a series of errors are reported.
I will report them one at a time in separate tickets, although they may have the same solution related to local.fields

Running the following:

`terraform apply -auto-approve -var="create_network=true" -var="create_bastion=true" -var="create_cluster=false" -var="monitoring=sumo"
`

Code block:
```
# Sumo Logic Fields sent via otelcol-sumo
## RR this keeps failing
resource "sumologic_field" "otc" {
  for_each = var.create_bastion ? toset(local.fields.otc) : toset([])

  field_name = each.key
  data_type  = "String"
  state      = "Enabled"
}
```

Error:

│ Error: {"id":"XTXOM-K8KCR-XV1Z0","errors":[{"code":"field:already_exists","message":"Field with the given name already exists"}]}
│
│   with module.sumo["gewq"].sumologic_field.otc["host.group"],
│   on modules/sumo/bastion.tf line 18, in resource "sumologic_field" "otc":
│   18: resource "sumologic_field" "otc" {

**Comment by jeff-d** [comment]
Hello! This is a known issue, called out here.

**Comment by jeff-d** [comment]
Reopening due to regression introduced in [cda310b](https://github.com/jeff-d/quicklab/commit/cda310b0ed72a6788bef3104842a97fe48b9563b).
